package com.example.compose

import androidx.compose.ui.graphics.Color

// ── Light scheme ──────────────────────────────────────────────────────────────
// Primary: Blue #2F80ED (CTA buttons, key numeric highlights)
val primaryLight = Color(0xFF2F80ED)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD6E8FF)
val onPrimaryContainerLight = Color(0xFF001A40)

// Secondary: Orange #F2994A (screenshots category, accent accents)
val secondaryLight = Color(0xFFF2994A)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFE5CC)
val onSecondaryContainerLight = Color(0xFF2D1600)

// Tertiary: Purple #9B51E0 (icon containers, progress ring, FABs)
val tertiaryLight = Color(0xFF9B51E0)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFF0E0FF)
val onTertiaryContainerLight = Color(0xFF3A0070)

// Error
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)

// Background / Surface
val backgroundLight = Color(0xFFFFFFFF)
val onBackgroundLight = Color(0xFF101828)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF101828)
val surfaceVariantLight = Color(0xFFF5F5F5)
val onSurfaceVariantLight = Color(0xFF4A5565)
val outlineLight = Color(0xFF6A7282)
val outlineVariantLight = Color(0xFFE5E7EB)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF1F2533)
val inverseOnSurfaceLight = Color(0xFFF5F5F5)
val inversePrimaryLight = Color(0xFFA8C8FF)
val surfaceDimLight = Color(0xFFE5E5E5)
val surfaceBrightLight = Color(0xFFFFFFFF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF9F9F9)
val surfaceContainerLight = Color(0xFFF5F5F5)
val surfaceContainerHighLight = Color(0xFFEFEFEF)
val surfaceContainerHighestLight = Color(0xFFE8E8E8)

// ── Light Medium Contrast ─────────────────────────────────────────────────────
val primaryLightMediumContrast = Color(0xFF1860C4)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF2F80ED)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFFC07020)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFFF2994A)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF7228C0)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF9B51E0)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFFFFFF)
val onBackgroundLightMediumContrast = Color(0xFF101828)
val surfaceLightMediumContrast = Color(0xFFFFFFFF)
val onSurfaceLightMediumContrast = Color(0xFF080E18)
val surfaceVariantLightMediumContrast = Color(0xFFF5F5F5)
val onSurfaceVariantLightMediumContrast = Color(0xFF32404F)
val outlineLightMediumContrast = Color(0xFF4A5565)
val outlineVariantLightMediumContrast = Color(0xFF6A7282)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF1F2533)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF5F5F5)
val inversePrimaryLightMediumContrast = Color(0xFFC0D8FF)
val surfaceDimLightMediumContrast = Color(0xFFD0D0D0)
val surfaceBrightLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF9F9F9)
val surfaceContainerLightMediumContrast = Color(0xFFEFEFEF)
val surfaceContainerHighLightMediumContrast = Color(0xFFE8E8E8)
val surfaceContainerHighestLightMediumContrast = Color(0xFFE0E0E0)

// ── Light High Contrast ───────────────────────────────────────────────────────
val primaryLightHighContrast = Color(0xFF003090)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF1860C4)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF804800)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFFC07020)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF4A0090)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF7228C0)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFFFFFF)
val onBackgroundLightHighContrast = Color(0xFF101828)
val surfaceLightHighContrast = Color(0xFFFFFFFF)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFF5F5F5)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF2A3444)
val outlineVariantLightHighContrast = Color(0xFF4A5565)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF1F2533)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFE8F0FF)
val surfaceDimLightHighContrast = Color(0xFFC0C0C0)
val surfaceBrightLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF5F5F5)
val surfaceContainerLightHighContrast = Color(0xFFE8E8E8)
val surfaceContainerHighLightHighContrast = Color(0xFFDCDCDC)
val surfaceContainerHighestLightHighContrast = Color(0xFFD0D0D0)

// ── Dark scheme ───────────────────────────────────────────────────────────────
val primaryDark = Color(0xFFA8C8FF)
val onPrimaryDark = Color(0xFF00315E)
val primaryContainerDark = Color(0xFF1A5A9E)
val onPrimaryContainerDark = Color(0xFFD6E8FF)
val secondaryDark = Color(0xFFFFB870)
val onSecondaryDark = Color(0xFF4A2000)
val secondaryContainerDark = Color(0xFF9A5C1A)
val onSecondaryContainerDark = Color(0xFFFFE5CC)
val tertiaryDark = Color(0xFFCF9FFF)
val onTertiaryDark = Color(0xFF4A0080)
val tertiaryContainerDark = Color(0xFF7228BF)
val onTertiaryContainerDark = Color(0xFFF0E0FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F1117)
val onBackgroundDark = Color(0xFFE4E6EF)
val surfaceDark = Color(0xFF0F1117)
val onSurfaceDark = Color(0xFFE4E6EF)
val surfaceVariantDark = Color(0xFF1E2333)
val onSurfaceVariantDark = Color(0xFF9AA5B4)
val outlineDark = Color(0xFF6B7585)
val outlineVariantDark = Color(0xFF2D3748)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE4E6EF)
val inverseOnSurfaceDark = Color(0xFF1F2533)
val inversePrimaryDark = Color(0xFF2F80ED)
val surfaceDimDark = Color(0xFF0A0D14)
val surfaceBrightDark = Color(0xFF343D52)
val surfaceContainerLowestDark = Color(0xFF07090F)
val surfaceContainerLowDark = Color(0xFF131720)
val surfaceContainerDark = Color(0xFF171C28)
val surfaceContainerHighDark = Color(0xFF1E2535)
val surfaceContainerHighestDark = Color(0xFF262F42)

// ── Dark Medium Contrast ──────────────────────────────────────────────────────
val primaryDarkMediumContrast = Color(0xFFC0D8FF)
val onPrimaryDarkMediumContrast = Color(0xFF002050)
val primaryContainerDarkMediumContrast = Color(0xFF3A80C0)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFFFC880)
val onSecondaryDarkMediumContrast = Color(0xFF3A1800)
val secondaryContainerDarkMediumContrast = Color(0xFFB06020)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFE0C0FF)
val onTertiaryDarkMediumContrast = Color(0xFF3A0070)
val tertiaryContainerDarkMediumContrast = Color(0xFFB070E8)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF0F1117)
val onBackgroundDarkMediumContrast = Color(0xFFE4E6EF)
val surfaceDarkMediumContrast = Color(0xFF0F1117)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF1E2333)
val onSurfaceVariantDarkMediumContrast = Color(0xFFBDC8D8)
val outlineDarkMediumContrast = Color(0xFF9AA5B4)
val outlineVariantDarkMediumContrast = Color(0xFF6B7585)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE4E6EF)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF1E2535)
val inversePrimaryDarkMediumContrast = Color(0xFF1860C4)
val surfaceDimDarkMediumContrast = Color(0xFF0A0D14)
val surfaceBrightDarkMediumContrast = Color(0xFF404C62)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF050709)
val surfaceContainerLowDarkMediumContrast = Color(0xFF171C28)
val surfaceContainerDarkMediumContrast = Color(0xFF202840)
val surfaceContainerHighDarkMediumContrast = Color(0xFF28334A)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF303D55)

// ── Dark High Contrast ────────────────────────────────────────────────────────
val primaryDarkHighContrast = Color(0xFFE8F0FF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFA8C8FF)
val onPrimaryContainerDarkHighContrast = Color(0xFF000F28)
val secondaryDarkHighContrast = Color(0xFFFFE8CC)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFFFB870)
val onSecondaryContainerDarkHighContrast = Color(0xFF180900)
val tertiaryDarkHighContrast = Color(0xFFF5E8FF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFCF9FFF)
val onTertiaryContainerDarkHighContrast = Color(0xFF1A0030)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF0F1117)
val onBackgroundDarkHighContrast = Color(0xFFE4E6EF)
val surfaceDarkHighContrast = Color(0xFF0F1117)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF1E2333)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFE4E6EF)
val outlineVariantDarkHighContrast = Color(0xFFD4BEB9)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE4E6EF)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF003090)
val surfaceDimDarkHighContrast = Color(0xFF0A0D14)
val surfaceBrightDarkHighContrast = Color(0xFF4A5870)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1F2533)
val surfaceContainerDarkHighContrast = Color(0xFF2D3748)
val surfaceContainerHighDarkHighContrast = Color(0xFF384455)
val surfaceContainerHighestDarkHighContrast = Color(0xFF435162)
